import "./globals.css";
import { MachineProvider } from "../context/MachineContext";
import { AccountProvider } from "../context/AccountContext";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Tigrinho App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={poppins.variables}>
        <AccountProvider>
          <MachineProvider>{children}</MachineProvider>
        </AccountProvider>
      </body>
    </html>
  );
}
